### ISSUE TITLE
Make tasselcap work

### ISSUE THREAD

**Issue by dutri001** [dutri001/bfastSpatial#46]
Sr2vi needs to retrieve sensor info using getsceneinfo and pass it as argument to .tc* function

**Comment by bendv** [comment]
I've edited the function to just use one set of SR-related coefficients for now @ fa4ca0e7e5537535c2212cc566b6cf6b43f77464. See 'details' section of the documentation for a warning on using the function for OLI data. We can revisit it later if we need to add different coefficients (esp. for OLI data).
