### ISSUE TITLE
Tasseled Cap coefficients

### ISSUE THREAD

**Issue by ceholden** [dutri001/bfastSpatial#51]
I ran into your `LandsatVIs.R` calculation of the Tasseled Cap for Landsat TM while trying to figure out the correct coefficients myself. The PDF scan of the Crist 1985 paper from RSE is so horrible that it's hard to see if some coefficients are positive or negative. I found some other papers documenting the coefficients and even found an alternative source for the Crist 1985 that is digitized in better resolution, and these sources show that some of the coefficients your code uses have the wrong sign.

The Crist 1985 rescan is available [here](http://www.gis.usu.edu/~doug/RS5750/assign/OLD/RSE(17)-301.pdf) and Meddens *et al* (2013) also published the coefficients in their [work available here](http://www.fs.fed.us/rm/pubs_other/rmrs_2013_meddens_a001.pdf).

The Wetness coefficient for Band 5 should be `-0.6806` and the Greenness coefficient for Band 5 should be `-0.0002`. Otherwise everything looks correct! I've used the wrong coefficients many times because of the poor quality of the PDF so hope I can help you solve the same small problem. 

Cheers

**Comment by dutri001** [comment]
Hi Chris,
Thanks a lot for spotting the errors and for the links. These TC components always gave us a hard time. We'll fix the code soon.
Cheers

**Comment by bendv** [comment]
I've updated the tc coefficients to just use a single set for SR data for now @ fa4ca0e7e5537535c2212cc566b6cf6b43f77464. I wrote a warning about applying this to OLI data because of bandwidth differences. I'll close this issue for now, but we can always revisit the coefficients as necessary.
